# Generated by Django 3.0.8 on 2020-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
