# Generated by Django 3.0.8 on 2020-09-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_auto_20200911_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=70)),
                ('wing', models.CharField(default='', max_length=2)),
                ('flat', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=20)),
                ('complaint', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
