# Generated by Django 3.0.8 on 2021-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(default='', max_length=30)),
                ('v_date', models.DateField()),
                ('v_number', models.CharField(default='', max_length=20)),
                ('v_purpose', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
