# Generated by Django 3.0.8 on 2021-03-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='msg_id',
            new_name='com_id',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='wing',
        ),
    ]
