# Generated by Django 3.0.8 on 2020-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=80)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='security/images')),
            ],
        ),
    ]
