# Generated by Django 3.0.8 on 2020-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='vote_groups',
            name='votes',
            field=models.IntegerField(default=0, max_length=2000),
        ),
        migrations.AlterField(
            model_name='vote_groups',
            name='image',
            field=models.ImageField(upload_to='security/images'),
        ),
    ]
