# Generated by Django 3.0.8 on 2021-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20201231_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startvote',
            fields=[
                ('start_id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Vote_count',
        ),
        migrations.RemoveField(
            model_name='vote_groups',
            name='votes',
        ),
    ]
