# Generated by Django 3.0.8 on 2021-02-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_vote_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField()),
                ('Flat_no', models.CharField(default='', max_length=10)),
                ('Due_date', models.DateField()),
                ('Period', models.CharField(default='', max_length=30)),
                ('Name', models.CharField(max_length=70)),
                ('All_municiple_due', models.CharField(default='', max_length=20)),
                ('Adminis_general_expenses', models.CharField(default='', max_length=20)),
                ('Sinking_funds', models.CharField(default='', max_length=20)),
                ('Periodic_build_mainten', models.CharField(default='', max_length=20)),
                ('CAU_parking', models.CharField(default='', max_length=20)),
                ('Non_Ocupancy_charg_miscelnous', models.CharField(default='', max_length=20)),
                ('Past_areas_contribution', models.CharField(default='', max_length=20)),
                ('Interest_due', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
