# Generated by Django 3.0.8 on 2021-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
