# Generated by Django 3.0.8 on 2021-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_maintenance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent_Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmain_id', models.IntegerField(default=0)),
                ('rbill_date', models.DateField()),
                ('rFlat_no', models.CharField(default='', max_length=10)),
                ('rDue_date', models.DateField()),
                ('rPeriod', models.CharField(default='', max_length=30)),
                ('rName', models.CharField(max_length=70)),
                ('rAll_municiple_due', models.CharField(default='', max_length=20)),
                ('rAdminis_general_expenses', models.CharField(default='', max_length=20)),
                ('rSinking_funds', models.CharField(default='', max_length=20)),
                ('rPeriodic_build_mainten', models.CharField(default='', max_length=20)),
                ('rCAU_parking', models.CharField(default='', max_length=20)),
                ('rNon_Ocupancy_charg_miscelnous', models.CharField(default='', max_length=20)),
                ('rPast_areas_contribution', models.CharField(default='', max_length=20)),
                ('rInterest_due', models.CharField(default='', max_length=20)),
                ('rAmount', models.IntegerField(default=0)),
            ],
        ),
    ]
