# Generated by Django 3.0.8 on 2021-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_recent_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_maintenance',
            name='id',
        ),
        migrations.AlterField(
            model_name='recent_maintenance',
            name='rmain_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
