# Generated by Django 3.0.8 on 2021-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20210218_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_reply',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_to', models.CharField(default='', max_length=20)),
                ('reply_msg', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
