# Generated by Django 3.0.8 on 2021-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_reply',
            name='sec_user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
