# Generated by Django 3.0.8 on 2021-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_complaint_reply_sec_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint_reply',
        ),
    ]
