# Generated by Django 3.0.8 on 2021-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_delete_complaint_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_detail',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_num', models.IntegerField(default=0)),
                ('bill_name', models.CharField(default='', max_length=70)),
                ('flat_num', models.CharField(default='', max_length=50)),
                ('bill_Date', models.DateField()),
                ('bill_amount', models.IntegerField(default=0)),
                ('m_order_id', models.CharField(default='', max_length=100)),
                ('m_payment_id', models.CharField(default='', max_length=100)),
                ('m_razorpay_signature', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
